"""Gaze prediction model combining Face2Step and Step2Latent stages.

End-to-end model that composes Face2StepModel for facial encoding and Step2LatentModel
for temporal processing to produce gaze predictions. Supports two training modes:
- "full": Two-stage pipeline (Face2Step + Step2Latent, both trainable)
- "encoder": Single-stage inference (Face2Step trainable, Step2Latent frozen)
"""

from typing import Any, Dict
import tensorflow as tf
from NN.models.Face2StepModel import Face2StepModel
from NN.models.Step2LatentModel import Step2LatentModel
from NN.models.NpzModelMixin import NpzModelMixin
from Core.logging_config import get_logger
from Core.Constants import VALID_TRAINING_MODES
from NN.Utils import structured_latent_dropout

logger = get_logger(__name__)


class GazePredictionModel(NpzModelMixin, tf.keras.Model):
    """End-to-end model for gaze prediction from facial data.

    Processes facial landmarks (points), eye images, embeddings, and time information
    through a composed architecture. Supports two training modes:
    - "full": Two-stage pipeline (Face2Step + Step2Latent, both trainable)
    - "encoder": Single-stage inference (Face2Step trainable, Step2Latent frozen)

    Both models are always built regardless of mode. In encoder mode, Step2Latent
    is created but frozen (trainable=False) to reduce memory and computational overhead
    during inference while maintaining model structure for potential fine-tuning.

    In "full" mode, gaze predictions are generated by wrapper using PredictorBlock
    on final_latent from Step2Latent (handled by ModelWrapper, not this model).

    Architecture:
        - Face2StepModel: Encodes facial data (landmarks + eyes) to latent representation
        - Step2LatentModel: Processes temporal sequences through Transformer encoder blocks
          (always created, frozen in encoder mode)

    Attributes:
        latent_size: Dimension of latent representations
        mode: Training mode ("full" or "encoder")
    """

    def __init__(
        self,
        latent_size: int = 64,
        mode: str = "full",
        scale_mult: float = 1.0,
        **kwargs: Any,
    ) -> None:
        """Initialize GazePredictionModel.

        Args:
            latent_size: Dimension of the latent representation (default: 64).
            mode: Training mode "full" (two-stage) or "encoder" (Face2Step only). Default: "full"
            scale_mult: Scaling multiplier for all dimensions (default: 1.0, no scaling).
                Must be positive. Used for creating scaled teacher models.
            **kwargs: Additional keyword arguments passed to parent Model class.

        Raises:
            ValueError: If latent_size not positive, mode not in VALID_TRAINING_MODES,
                or scale_mult not positive.
        """
        super().__init__(**kwargs)

        # Input validation
        if latent_size <= 0:
            raise ValueError(f"latent_size must be positive, got {latent_size}")
        if mode not in VALID_TRAINING_MODES:
            raise ValueError(f"mode must be one of {VALID_TRAINING_MODES}, got {mode}")
        if scale_mult <= 0:
            raise ValueError(f"scale_mult must be positive, got {scale_mult}")

        self._latent_size: int = latent_size
        self._scale_mult: float = scale_mult
        self.latent_size: int = latent_size  # Store base for get_config
        self.mode: str = mode

        # CRITICAL: Pass base latent_size and scale_mult to sub-models
        # Sub-models independently compute scaled dimensions: int(latent_size * scale_mult)
        # This prevents double-scaling bug where scale_mult gets applied twice
        self.face2step = Face2StepModel(
            latent_size=latent_size,
            scale_mult=scale_mult,
            name="Face2Step",
        )

        # Always build Step2Latent
        self.step2latent = Step2LatentModel(
            latent_size=latent_size,
            scale_mult=scale_mult,
            name="Step2Latent",
        )

    def build(self, input_shape: Dict[str, Any]) -> None:
        """Build the model layers.

        Args:
            input_shape: Dictionary with keys for each input type and their shapes.
        """
        # Compute scaled latent_size for build shape calculation
        # Face2StepModel outputs scaled dimensions, which Step2LatentModel receives as input
        scaled_latent_size = int(self.latent_size * self._scale_mult)

        # Build sub-models to ensure proper layer configuration
        self.face2step.build(input_shape)
        self.step2latent.build(
            {
                "latent": (
                    input_shape.get("points", [])[0],
                    input_shape.get("points", [])[1],
                    scaled_latent_size,  # Use scaled latent_size as Face2Step outputs scaled dimensions
                ),
                "time": input_shape.get("time", ()),
                "embeddings": input_shape.get("embeddings", ()),
            }
        )
        super().build(input_shape)

    def call(
        self, inputs: Dict[str, tf.Tensor], training: bool = False
    ) -> Dict[str, tf.Tensor]:
        """Process facial data through the gaze prediction pipeline.

        In "full" mode: Encodes facial data (Face2Step stage) then processes temporal
        sequences (Step2Latent stage) to produce both intermediate and final latent
        representations.

        In "encoder" mode: Only encodes facial data (Face2Step stage), skips temporal
        processing. Returns intermediate_latent as both intermediate and final.

        Args:
            inputs: Dictionary containing:
                - 'points': Facial mesh points of shape (batch, seq_len, 478, 2)
                - 'left eye': Left eye image of shape (batch, seq_len, 32, 32, 1)
                - 'right eye': Right eye image of shape (batch, seq_len, 32, 32, 1)
                - 'time': Time values of shape (batch, seq_len, 1)
                - 'userId': User ID embedding of shape (batch, seq_len, emb_size)
                - 'screenId': Screen ID embedding of shape (batch, seq_len, emb_size)
                - 'cameraId': Camera ID embedding of shape (batch, seq_len, emb_size)
                - 'monitorId': Monitor ID embedding of shape (batch, seq_len, emb_size)
                - 'placeId': Place ID embedding of shape (batch, seq_len, emb_size)
                  (concatenated together to form embeddings of shape (batch, seq_len, 5*emb_size))
            training: Boolean indicating training or inference mode.

        Returns:
            Dictionary with:
                - 'intermediate_latent': Intermediate latent from Face2Step of shape (batch, seq_len, latent_size)
                - 'final_latent': Final latent from Step2Latent (full mode) or intermediate_latent (encoder mode)
                  of shape (batch, seq_len, latent_size)
        """
        embeddings = structured_latent_dropout(inputs["embeddings"], training=training)
        # Face2Step: Encode facial data to latent representation
        face2step_inputs = {
            "points": inputs["points"],
            "left eye": inputs["left eye"],
            "right eye": inputs["right eye"],
            "embeddings": embeddings,
        }
        latent_intermediate = self.face2step(face2step_inputs, training=training)
        latent_final = tf.stop_gradient(latent_intermediate)

        # Select which latent to use as final based on mode
        if self.mode == "full":
            step2latent_inputs = {
                "latent": structured_latent_dropout(
                    latent_intermediate, training=training
                ),
                "time": inputs["time"],
                "embeddings": embeddings,
            }
            latent_final = self.step2latent(step2latent_inputs, training=training)

        return {
            "intermediate_latent": latent_intermediate,
            "final_latent": latent_final,
        }
