"""Constants for neural network models and layers."""

from typing import Literal

# Activation functions
STANDARD_NONNEGATIVE_ACTIVATION = "relu"

# Eye encoder architecture
EYE_ENCODER_CONV_FILTERS = [32, 32]
EYE_ENCODER_CONV_STRIDE = 2
EYE_ENCODER_CONV_KERNEL = 3
EYE_ENCODER_CONV_PADDING: Literal["same", "valid"] = "same"

# Eye encoder conv2latent architecture
EYE_ENCODER_CONV2LATENT_CONV_PE_CHANNELS = 16 - 2
EYE_ENCODER_CONV2LATENT_CONV_KERNEL_3 = 3
EYE_ENCODER_CONV2LATENT_INIT_SIZE = 8
EYE_ENCODER_CONV2LATENT_INIT_CHANNELS = 64

# Step2Latent model architecture
STEP2LATENT_TRANSFORMER_BLOCKS = 3
STEP2LATENT_MLP_SIZES = 3
STEP2LATENT_MLP_ACTIVATION = STANDARD_NONNEGATIVE_ACTIVATION
STEP2LATENT_TRANSFORMER_NUM_HEADS = 16
STEP2LATENT_TRANSFORMER_DFF_MULTIPLIER = 16
STEP2LATENT_TRANSFORMER_DROPOUT_RATE = 0.01

# Face2Step model architecture
FACE2STEP_FUSION_BLOCKS = 3
FACE2STEP_MLP_SIZES = 3
FACE2STEP_MLP_ACTIVATION = STANDARD_NONNEGATIVE_ACTIVATION

# PredictorBlock layer
PREDICTOR_BLOCK_MLP_SIZES = [128, 128, 128]
PREDICTOR_BLOCK_ACTIVATION = STANDARD_NONNEGATIVE_ACTIVATION
PREDICTOR_BLOCK_SHIFT = 0.5
PREDICTOR_BLOCK_OUTPUT_DIMS = 2
PREDICTOR_BLOCK_FULL_MODE_MLP_SIZE = 256

# Face2Step model architecture - MLP size multipliers
FACE2STEP_MLP_MULTIPLIER_LARGE = 3
FACE2STEP_MLP_MULTIPLIER_MEDIUM = 2
FACE2STEP_MLP_MULTIPLIER_SMALL = 1

# Default hyperparameters
DEFAULT_EMBEDDING_SIZE = 64
DEFAULT_LATENT_SIZE = 256

# Face mesh and eye constants
FACE_MESH_POINTS = 478
EYE_SIZE = 32

# MultiHeadAttention layer constants
ATTENTION_MASK_VALUE = -1e9

# PredictorFace layer constants
FACE_VALIDITY_THRESHOLD = 0.5

# TimeEncodingLayer constants
TIME_NORMALIZATION_EPSILON = 1e-8

# sMLP module level dropout
SMLP_GLOBAL_DROPOUT = 0.01
